### ISSUE TITLE
作者可以参考今日热榜 https://tophub.today/ 

### ISSUE THREAD

**Issue by wx962464** [timeromantic/hotDataList#15]
进行更多的新闻聚合的完善，增加日期，可以展示历史的每天数据，不确定作者现在每隔多久进行一次爬数据~，

**Comment by timeromantic** [comment]
你好，谢谢你的建议，目前数据的更新率是每半个小时爬虫会爬一次，然后，关于历史数据这个已经在参考你提到的tophub.today，目前打算重构后端的的mysql替换成mangodb。版本做好了，会通知你的，最后，欢迎光顾我的网页。

**Comment by wx962464** [comment]
好的，非常感谢~，准备在你这个基础上，弄个微信小程序，哈哈~
