### ISSUE TITLE
如何在windows下启动服务

### ISSUE THREAD

**Issue by JimReno** [timeromantic/hotDataList#27]
请问在windows下是如何配置的，萌新刚接触这个项目，对go和mysql也是新手，因此对大佬
`“执行database.sql创建数据库,并配置/Config/Mysql.go数据库连接地址”`的精炼语言不是很理解,没有能够读懂整个安装步骤。看到issue部分感觉大家都能成功运行，所以自己搞了两天，但是并没有能够成功编译，但仍然执着于这个项目。

目前下载了go的idle goland，安装好了mysql，学习了go和mysql语法。
我已看到[issue#8](https://github.com/tophubs/TopList/issues/8)相关说明，有木有大佬指导一下哈：）

**Comment by hellokaton** [comment]
这和操作系统关系不大。

> 前提：由于项目中依赖了很多第三方库，你需要手动将他们先 go get 一下

**配置数据库**

1. 你需要创建数据库并导入 `database.sql` 的脚本
2. 你需要修改 `Config/MySql.go` 文件中的数据库配置

这个时候配置类的已经完成，如果在本地启动，大概是这样：

1. 启动 http 服务端，执行 `go run App/Server.go` 即可
2. 执行爬虫任务（因为是本地暂时不用定时任务），执行 `go run App/GetHot.go` 即可
3. 使用浏览器打开 `Html/hot.html` 文件，使用 goland 直接右击使用浏览器打开就可以。

**Comment by JimReno** [comment]
**执行客户端文件出错**

按照大佬的步骤，mysql的数据库应该是导入了（尴尬）
![image](https://user-images.githubusercontent.com/28293145/64105556-0f37e800-cda9-11e9-9a60-cc84e4c3cfe2.png)

config没有修改，发现涉及到文件目录的都是相对路径。

配置完成后，启动了http服务端：
![image](https://user-images.githubusercontent.com/28293145/64105727-5d4ceb80-cda9-11e9-83d7-cd4a2ab2a13b.png)

**执行用户端的地方出现问题**`go run APP/GetHot.go`，会报错：`2019/09/02 17:45:57 错误：dial tcp: lookup tcp/port: getaddrinfow: The specified class was not found.`
![image](https://user-images.githubusercontent.com/28293145/64105844-8ff6e400-cda9-11e9-88e4-fd1c4e46c032.png)

google了并没有出现能够解决这个问题的结果，搜索了issue也没有找到对应的解决方案 T.T，还请大佬帮忙判断一下哪里出了问题：）

**Comment by mark988** [comment]
syscall.SIGUSR1  windows 下编译报错。

**Comment by mark988** [comment]
Administrator@WINDOWS-O8ROA6P MINGW32 /e/project-example/go-project
$ go run App/Server.go
parse mysql config once. filePath: E:\project-example\go-project\Config\mysql.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x74c784]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        D:/Go/src/sync/mutex.go:74
database/sql.(*DB).SetMaxOpenConns(0x0, 0x7d0)
        D:/Go/src/database/sql/sql.go:899 +0x34
_/E_/project-example/go-project/Common.init.0()
        E:/project-example/go-project/Common/Db.go:41 +0xe7
exit status 2

Administrator@WINDOWS-O8ROA6P MINGW32 /e/project-example/go-project

**Comment by JimReno** [comment]
@mark988 可以看下这个 https://github.com/tophubs/TopList/issues/8 应该能解决你的问题

**Comment by h1z3y3** [comment]
#53
