### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by mark988** [timeromantic/hotDataList#37]
Config\MySql.go:5:2: cannot find package "github.com/BurntSushi/toml" in any of:
        D:\Go\src\github.com\BurntSushi\toml (from $GOROOT)
        E:\project-example\go-project\src\github.com\BurntSushi\toml (from $GOPATH)
App\GetHot.go:8:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
        D:\Go\src\github.com\PuerkitoBio\goquery (from $GOROOT)
        E:\project-example\go-project\src\github.com\PuerkitoBio\goquery (from $GOPATH)
App\GetHot.go:9:2: cannot find package "github.com/bitly/go-simplejson" in any of:
        D:\Go\src\github.com\bitly\go-simplejson (from $GOROOT)
        E:\project-example\go-project\src\github.com\bitly\go-simplejson (from $GOPATH)
Common\Db.go:7:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
        D:\Go\src\github.com\go-sql-driver\mysql (from $GOROOT)
        E:\project-example\go-project\src\github.com\go-sql-driver\mysql (from $GOPATH)
App\GetHot.go:10:2: cannot find package "golang.org/x/text/encoding/simplifiedchinese" in any of:
        D:\Go\src\golang.org\x\text\encoding\simplifiedchinese (from $GOROOT)
        E:\project-example\go-project\src\golang.org\x\text\encoding\simplifiedchinese (from $GOPATH)
App\GetHot.go:11:2: cannot find package "golang.org/x/text/transform" in any of:
        D:\Go\src\golang.org\x\text\transform (from $GOROOT)
        E:\project-example\go-project\src\golang.org\x\text\transform (from $GOPATH)

**Comment by timeromantic** [comment]
依赖的库缺失
cannot find package
github.com/BurntSushi/toml  
这些程序依赖的运行库没有
