### ISSUE TITLE
执行server  hotget 都报错

### ISSUE THREAD

**Issue by mark988** [timeromantic/hotDataList#39]
Administrator@WINDOWS-O8ROA6P MINGW32 /e/project-example/go-project
$ go run App/Server.go
parse mysql config once. filePath: E:\project-example\go-project\Config\mysql.toml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x20 pc=0x74c784]

goroutine 1 [running]:
sync.(*Mutex).Lock(...)
        D:/Go/src/sync/mutex.go:74
database/sql.(*DB).SetMaxOpenConns(0x0, 0x7d0)
        D:/Go/src/database/sql/sql.go:899 +0x34
_/E_/project-example/go-project/Common.init.0()
        E:/project-example/go-project/Common/Db.go:41 +0xe7
exit status 2

Administrator@WINDOWS-O8ROA6P MINGW32 /e/project-example/go-project

**Comment by timeromantic** [comment]
项目路径有问题。不能找到配置文件

**Comment by mark988** [comment]
怎么写比较好？

**Comment by mark988** [comment]
怎么才能找到配置文件？
